version: '3'

services:
  softether:
    image: ajleal/softether
    cap_add:
      - NET_ADMIN
    restart: always
    ports:
      #  - 53:53
      - 444:443
      - 992:992
      - 1194:1194/udp
      - 5555:5555
      - 500:500/udp
      - 4500:4500/udp
      #  - 1701:1701/udp
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./softether_log:/usr/local/vpnserver/server_log"
      - "./softether_packetlog:/usr/local/vpnserver/packet_log"
      - "./softether_securitylog:/usr/local/vpnserver/security_log"
