# Docker Compose file for running a SoftEther VPN server
services:
  app:
    image: ajleal/softether
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      # Port mappings for SoftEther VPN Server
      - 500:500/udp
      - 4500:4500/udp
      - 1701:1701/tcp
      - 1194:1194/udp
      - 5555:5555/tcp
      - 5555:5555/udp
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./softether_data:/var/lib/softether"
      - "./softether_log:/var/log/softether"
